/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafkapoc.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DirectDiscountAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6769002494384028392L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DirectDiscountAvro\",\"namespace\":\"com.example.kafkapoc.avro\",\"fields\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"directDiscount\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DirectDiscountAvro> ENCODER =
      new BinaryMessageEncoder<DirectDiscountAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DirectDiscountAvro> DECODER =
      new BinaryMessageDecoder<DirectDiscountAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DirectDiscountAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DirectDiscountAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DirectDiscountAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DirectDiscountAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DirectDiscountAvro from a ByteBuffer. */
  public static DirectDiscountAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence sku;
  @Deprecated public java.lang.CharSequence directDiscount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DirectDiscountAvro() {}

  /**
   * All-args constructor.
   * @param sku The new value for sku
   * @param directDiscount The new value for directDiscount
   */
  public DirectDiscountAvro(java.lang.CharSequence sku, java.lang.CharSequence directDiscount) {
    this.sku = sku;
    this.directDiscount = directDiscount;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sku;
    case 1: return directDiscount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sku = (java.lang.CharSequence)value$; break;
    case 1: directDiscount = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.CharSequence getSku() {
    return sku;
  }

  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.CharSequence value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'directDiscount' field.
   * @return The value of the 'directDiscount' field.
   */
  public java.lang.CharSequence getDirectDiscount() {
    return directDiscount;
  }

  /**
   * Sets the value of the 'directDiscount' field.
   * @param value the value to set.
   */
  public void setDirectDiscount(java.lang.CharSequence value) {
    this.directDiscount = value;
  }

  /**
   * Creates a new DirectDiscountAvro RecordBuilder.
   * @return A new DirectDiscountAvro RecordBuilder
   */
  public static com.example.kafkapoc.avro.DirectDiscountAvro.Builder newBuilder() {
    return new com.example.kafkapoc.avro.DirectDiscountAvro.Builder();
  }

  /**
   * Creates a new DirectDiscountAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DirectDiscountAvro RecordBuilder
   */
  public static com.example.kafkapoc.avro.DirectDiscountAvro.Builder newBuilder(com.example.kafkapoc.avro.DirectDiscountAvro.Builder other) {
    return new com.example.kafkapoc.avro.DirectDiscountAvro.Builder(other);
  }

  /**
   * Creates a new DirectDiscountAvro RecordBuilder by copying an existing DirectDiscountAvro instance.
   * @param other The existing instance to copy.
   * @return A new DirectDiscountAvro RecordBuilder
   */
  public static com.example.kafkapoc.avro.DirectDiscountAvro.Builder newBuilder(com.example.kafkapoc.avro.DirectDiscountAvro other) {
    return new com.example.kafkapoc.avro.DirectDiscountAvro.Builder(other);
  }

  /**
   * RecordBuilder for DirectDiscountAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DirectDiscountAvro>
    implements org.apache.avro.data.RecordBuilder<DirectDiscountAvro> {

    private java.lang.CharSequence sku;
    private java.lang.CharSequence directDiscount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafkapoc.avro.DirectDiscountAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.directDiscount)) {
        this.directDiscount = data().deepCopy(fields()[1].schema(), other.directDiscount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DirectDiscountAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafkapoc.avro.DirectDiscountAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.directDiscount)) {
        this.directDiscount = data().deepCopy(fields()[1].schema(), other.directDiscount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.CharSequence getSku() {
      return sku;
    }

    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.DirectDiscountAvro.Builder setSku(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sku = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.DirectDiscountAvro.Builder clearSku() {
      sku = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'directDiscount' field.
      * @return The value.
      */
    public java.lang.CharSequence getDirectDiscount() {
      return directDiscount;
    }

    /**
      * Sets the value of the 'directDiscount' field.
      * @param value The value of 'directDiscount'.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.DirectDiscountAvro.Builder setDirectDiscount(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.directDiscount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'directDiscount' field has been set.
      * @return True if the 'directDiscount' field has been set, false otherwise.
      */
    public boolean hasDirectDiscount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'directDiscount' field.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.DirectDiscountAvro.Builder clearDirectDiscount() {
      directDiscount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DirectDiscountAvro build() {
      try {
        DirectDiscountAvro record = new DirectDiscountAvro();
        record.sku = fieldSetFlags()[0] ? this.sku : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.directDiscount = fieldSetFlags()[1] ? this.directDiscount : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DirectDiscountAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<DirectDiscountAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DirectDiscountAvro>
    READER$ = (org.apache.avro.io.DatumReader<DirectDiscountAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
