/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.kafkapoc.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PromoDiscountAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3234300563759930979L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PromoDiscountAvro\",\"namespace\":\"com.example.kafkapoc.avro\",\"fields\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"promoDiscount\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PromoDiscountAvro> ENCODER =
      new BinaryMessageEncoder<PromoDiscountAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PromoDiscountAvro> DECODER =
      new BinaryMessageDecoder<PromoDiscountAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PromoDiscountAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PromoDiscountAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PromoDiscountAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PromoDiscountAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PromoDiscountAvro from a ByteBuffer. */
  public static PromoDiscountAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence sku;
  @Deprecated public java.lang.CharSequence promoDiscount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PromoDiscountAvro() {}

  /**
   * All-args constructor.
   * @param sku The new value for sku
   * @param promoDiscount The new value for promoDiscount
   */
  public PromoDiscountAvro(java.lang.CharSequence sku, java.lang.CharSequence promoDiscount) {
    this.sku = sku;
    this.promoDiscount = promoDiscount;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sku;
    case 1: return promoDiscount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sku = (java.lang.CharSequence)value$; break;
    case 1: promoDiscount = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.CharSequence getSku() {
    return sku;
  }

  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.CharSequence value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'promoDiscount' field.
   * @return The value of the 'promoDiscount' field.
   */
  public java.lang.CharSequence getPromoDiscount() {
    return promoDiscount;
  }

  /**
   * Sets the value of the 'promoDiscount' field.
   * @param value the value to set.
   */
  public void setPromoDiscount(java.lang.CharSequence value) {
    this.promoDiscount = value;
  }

  /**
   * Creates a new PromoDiscountAvro RecordBuilder.
   * @return A new PromoDiscountAvro RecordBuilder
   */
  public static com.example.kafkapoc.avro.PromoDiscountAvro.Builder newBuilder() {
    return new com.example.kafkapoc.avro.PromoDiscountAvro.Builder();
  }

  /**
   * Creates a new PromoDiscountAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PromoDiscountAvro RecordBuilder
   */
  public static com.example.kafkapoc.avro.PromoDiscountAvro.Builder newBuilder(com.example.kafkapoc.avro.PromoDiscountAvro.Builder other) {
    return new com.example.kafkapoc.avro.PromoDiscountAvro.Builder(other);
  }

  /**
   * Creates a new PromoDiscountAvro RecordBuilder by copying an existing PromoDiscountAvro instance.
   * @param other The existing instance to copy.
   * @return A new PromoDiscountAvro RecordBuilder
   */
  public static com.example.kafkapoc.avro.PromoDiscountAvro.Builder newBuilder(com.example.kafkapoc.avro.PromoDiscountAvro other) {
    return new com.example.kafkapoc.avro.PromoDiscountAvro.Builder(other);
  }

  /**
   * RecordBuilder for PromoDiscountAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PromoDiscountAvro>
    implements org.apache.avro.data.RecordBuilder<PromoDiscountAvro> {

    private java.lang.CharSequence sku;
    private java.lang.CharSequence promoDiscount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.kafkapoc.avro.PromoDiscountAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.promoDiscount)) {
        this.promoDiscount = data().deepCopy(fields()[1].schema(), other.promoDiscount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PromoDiscountAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.kafkapoc.avro.PromoDiscountAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.promoDiscount)) {
        this.promoDiscount = data().deepCopy(fields()[1].schema(), other.promoDiscount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.CharSequence getSku() {
      return sku;
    }

    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.PromoDiscountAvro.Builder setSku(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sku = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.PromoDiscountAvro.Builder clearSku() {
      sku = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'promoDiscount' field.
      * @return The value.
      */
    public java.lang.CharSequence getPromoDiscount() {
      return promoDiscount;
    }

    /**
      * Sets the value of the 'promoDiscount' field.
      * @param value The value of 'promoDiscount'.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.PromoDiscountAvro.Builder setPromoDiscount(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.promoDiscount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'promoDiscount' field has been set.
      * @return True if the 'promoDiscount' field has been set, false otherwise.
      */
    public boolean hasPromoDiscount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'promoDiscount' field.
      * @return This builder.
      */
    public com.example.kafkapoc.avro.PromoDiscountAvro.Builder clearPromoDiscount() {
      promoDiscount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PromoDiscountAvro build() {
      try {
        PromoDiscountAvro record = new PromoDiscountAvro();
        record.sku = fieldSetFlags()[0] ? this.sku : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.promoDiscount = fieldSetFlags()[1] ? this.promoDiscount : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PromoDiscountAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<PromoDiscountAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PromoDiscountAvro>
    READER$ = (org.apache.avro.io.DatumReader<PromoDiscountAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
